import type { AutomotiveProduct } from "@/lib/content-schema";
import { mapContentSchema } from "@/lib/content-schema";
import { productReportDetails, reportOverview } from "@/content/report-enrichment";

const product = <const T extends keyof typeof productReportDetails>(
  id: T,
  details: Omit<AutomotiveProduct, "id" | "productionStatus" | "oemAdoption" | "keyInsight">,
) => ({
  id,
  ...details,
  ...productReportDetails[id],
});

export const edgeAIMapContent = mapContentSchema.parse({
  hero: {
    eyebrow: "Edge AI x Automotive",
    title: "車用電子 AI 產品全景圖",
    description:
      "從感測融合、座艙智能到車聯網與能源管理，將車用 Edge AI 產品、端側推論方案與晶片平台整理成可探索的互動地圖。",
  },
  reportOverview,
  categories: [
    {
      id: "adas",
      icon: "🛡️",
      category: "ADAS 先進駕駛輔助",
      color: "#E63946",
      summary: "聚焦高即時性、高功能安全需求的環境感知與決策控制。",
      products: [
        product("adas-forward-camera-module", {
          name: "前向攝影機模組",
          ai: "物件偵測 / 車道辨識 / 交通號誌識別",
          edge: "CNN 即時推論 (YOLOv8-nano / MobileNet)",
          chip: "TI TDA4VM / Mobileye EyeQ",
          priority: "high",
          vendors: ["TI", "Mobileye"],
          tags: ["vision", "adas"],
        }),
        product("adas-around-view-monitor", {
          name: "環景攝影機系統 (AVM)",
          ai: "3D 環景拼接 / 障礙物偵測 / 自動停車輔助",
          edge: "魚眼鏡頭畸變校正 + BEV 感知",
          chip: "Renesas R-Car V4H / Qualcomm SA8650P",
          priority: "high",
          vendors: ["Renesas", "Qualcomm"],
          tags: ["bev", "parking"],
        }),
        product("adas-mmwave-radar-module", {
          name: "毫米波雷達模組",
          ai: "目標追蹤 / 速度估算 / 碰撞預警 (FCW/AEB)",
          edge: "CFAR + 點雲聚類 + 追蹤濾波",
          chip: "TI AWR2944 / NXP S32R45",
          priority: "high",
          vendors: ["TI", "NXP"],
          tags: ["radar", "safety"],
        }),
        product("adas-lidar-module", {
          name: "光達 LiDAR 模組",
          ai: "3D 點雲語意分割 / SLAM 建圖",
          edge: "PointPillars / CenterPoint 即時推論",
          chip: "NVIDIA Orin / Mobileye Chauffeur",
          priority: "high",
          vendors: ["NVIDIA", "Mobileye"],
          tags: ["lidar", "slam"],
        }),
        product("adas-ultrasonic-array", {
          name: "超音波感測器陣列",
          ai: "近距障礙物偵測 / 自動停車 (APA)",
          edge: "ToF 融合 + 佔據柵格推論",
          chip: "NXP S32K3 + 專用 MCU",
          priority: "mid",
          vendors: ["NXP"],
          tags: ["sensor-fusion", "apa"],
        }),
        product("adas-fusion-ecu", {
          name: "感測融合控制器 (Fusion ECU)",
          ai: "多感測器融合決策 / 路徑規劃",
          edge: "Transformer BEV 融合模型",
          chip: "NVIDIA Orin-X / Qualcomm Ride",
          priority: "high",
          vendors: ["NVIDIA", "Qualcomm"],
          tags: ["fusion", "planning"],
        }),
      ],
    },
    {
      id: "cabin",
      icon: "🧑‍✈️",
      category: "座艙智能監控",
      color: "#457B9D",
      summary: "把駕駛行為、車內感知與多模態互動整合到單一智慧座艙體驗。",
      products: [
        product("cabin-driver-monitoring-system", {
          name: "駕駛監控系統 (DMS)",
          ai: "疲勞偵測 / 分心偵測 / 視線追蹤",
          edge: "人臉 Landmark + 眨眼頻率 + 頭部姿態推論",
          chip: "Seeing Machines Occula / TI TDA4",
          priority: "high",
          vendors: ["Seeing Machines", "TI"],
          tags: ["dms", "vision"],
        }),
        product("cabin-occupant-monitoring-system", {
          name: "乘客監控系統 (OMS)",
          ai: "乘客計數 / 兒童遺留偵測 / 安全帶偵測",
          edge: "輕量人體骨架偵測模型",
          chip: "Ambarella CV72 / NXP i.MX 8M Plus",
          priority: "mid",
          vendors: ["Ambarella", "NXP"],
          tags: ["oms", "safety"],
        }),
        product("cabin-gesture-recognition-module", {
          name: "手勢辨識模組",
          ai: "非接觸式手勢操控 (空調/音量/接聽)",
          edge: "3D ToF + CNN 手勢分類",
          chip: "Infineon REAL3 + 專用 NPU",
          priority: "mid",
          vendors: ["Infineon"],
          tags: ["gesture", "tof"],
        }),
        product("cabin-voice-ai-assistant", {
          name: "車內語音助理 (Voice AI)",
          ai: "離線語音辨識 / NLU 意圖解析 / TTS 語音合成",
          edge: "Whisper-tiny / 端側 LLM (Phi-3 mini)",
          chip: "Qualcomm SA8295P / MediaTek Dimensity Auto",
          priority: "high",
          vendors: ["Qualcomm", "MediaTek"],
          tags: ["voice", "llm"],
        }),
        product("cabin-air-quality-sensor", {
          name: "車內空氣品質感測器",
          ai: "PM2.5/VOC/CO₂ 預測與空調自動調節",
          edge: "時序預測模型 + PID 控制策略",
          chip: "Bosch BME688 + 車用 MCU",
          priority: "low",
          vendors: ["Bosch"],
          tags: ["air-quality", "time-series"],
        }),
        product("cabin-biometric-auth-module", {
          name: "生物特徵辨識模組",
          ai: "人臉解鎖 / 指紋啟動 / 座椅記憶連動",
          edge: "ArcFace-lite 特徵比對 + Anti-spoofing",
          chip: "NXP EdgeLock SE + i.MX RT",
          priority: "mid",
          vendors: ["NXP"],
          tags: ["biometric", "security"],
        }),
      ],
    },
    {
      id: "ivi",
      icon: "🎛️",
      category: "車載資訊娛樂 (IVI)",
      color: "#2A9D8F",
      summary: "圍繞個人化內容、智慧 UI 與車載連網形成多屏互動體驗。",
      products: [
        product("ivi-smart-central-display", {
          name: "中控智慧螢幕主機",
          ai: "個人化推薦 / 情境式 UI / AR 導航疊加",
          edge: "推薦引擎 + On-device LLM 對話",
          chip: "Qualcomm SA8295P / Samsung Exynos Auto V920",
          priority: "high",
          vendors: ["Qualcomm", "Samsung"],
          tags: ["ivi", "recommendation"],
        }),
        product("ivi-digital-cluster", {
          name: "數位儀表板 (Digital Cluster)",
          ai: "動態 HUD 資訊排序 / 駕駛風格適配",
          edge: "注意力優先級模型",
          chip: "Renesas R-Car S4 / TI Jacinto 7",
          priority: "mid",
          vendors: ["Renesas", "TI"],
          tags: ["cluster", "hud"],
        }),
        product("ivi-rear-seat-entertainment", {
          name: "後座娛樂螢幕",
          ai: "內容推薦 / 家長控制 / 多螢互動",
          edge: "邊緣推薦 + 串流優化",
          chip: "MediaTek MT8678 / Qualcomm QCS8550",
          priority: "low",
          vendors: ["MediaTek", "Qualcomm"],
          tags: ["entertainment", "streaming"],
        }),
        product("ivi-connectivity-tbox", {
          name: "車載 Wi-Fi / 5G T-Box",
          ai: "網路切片選擇 / OTA 差分更新排程",
          edge: "連線品質預測 + 流量調度",
          chip: "Qualcomm SDX75 / Samsung Exynos Modem",
          priority: "mid",
          vendors: ["Qualcomm", "Samsung"],
          tags: ["connectivity", "ota"],
        }),
        product("ivi-ar-hud", {
          name: "車載 AR-HUD 抬頭顯示器",
          ai: "AR 路標疊加 / 導航箭頭貼合路面",
          edge: "道路平面估計 + 即時渲染",
          chip: "TI DLP + Qualcomm SA8295P",
          priority: "mid",
          vendors: ["TI", "Qualcomm"],
          tags: ["ar-hud", "rendering"],
        }),
      ],
    },
    {
      id: "ev",
      icon: "⚡",
      category: "電動車動力與能源",
      color: "#E9C46A",
      summary: "將電池、驅動與熱管理的預測控制能力推進到車端即時決策。",
      products: [
        product("ev-battery-management-system", {
          name: "電池管理系統 (BMS)",
          ai: "SOC/SOH 預測 / 熱失控預警 / 均衡策略優化",
          edge: "LSTM/Transformer 時序模型 + 異常偵測",
          chip: "TI BQ79718 + C2000 MCU",
          priority: "high",
          vendors: ["TI"],
          tags: ["bms", "battery"],
        }),
        product("ev-motor-controller", {
          name: "馬達控制器 (MCU Inverter)",
          ai: "效率最佳化扭矩分配 / 故障預診斷",
          edge: "RL 控制策略 + 振動頻譜分析",
          chip: "Infineon AURIX TC4xx / NXP S32E",
          priority: "mid",
          vendors: ["Infineon", "NXP"],
          tags: ["motor", "control"],
        }),
        product("ev-smart-charging-module", {
          name: "智慧充電模組 (EVSE/OBC)",
          ai: "充電排程 / 電網負載預測 / V2G 策略",
          edge: "時序預測 + 強化學習調度",
          chip: "ST SPC58 + 通訊 MCU",
          priority: "mid",
          vendors: ["ST"],
          tags: ["charging", "v2g"],
        }),
        product("ev-energy-regeneration-controller", {
          name: "能量回收控制器",
          ai: "再生制動力道 AI 適配 / 駕駛習慣學習",
          edge: "輕量 RL Agent + 地形感知模型",
          chip: "Infineon AURIX + 慣性感測器",
          priority: "mid",
          vendors: ["Infineon"],
          tags: ["regeneration", "rl"],
        }),
        product("ev-thermal-management-controller", {
          name: "熱管理控制器",
          ai: "電池/馬達/座艙聯合熱管理 AI 排程",
          edge: "多目標最佳化 + 數位孿生",
          chip: "NXP S32K3 + 多路溫度感測",
          priority: "low",
          vendors: ["NXP"],
          tags: ["thermal", "digital-twin"],
        }),
      ],
    },
    {
      id: "chassis",
      icon: "🏎️",
      category: "底盤與安全",
      color: "#F4A261",
      summary: "把即時控制、車輛動態估測與功能安全整合到核心底盤域。",
      products: [
        product("chassis-electronic-stability-control", {
          name: "電子穩定控制 (ESC/ESP)",
          ai: "路面摩擦係數估算 / 側滑預測",
          edge: "即時狀態估測 Kalman + ML 融合",
          chip: "Infineon AURIX TC3xx / NXP S32S",
          priority: "high",
          vendors: ["Infineon", "NXP"],
          tags: ["esc", "safety"],
        }),
        product("chassis-electronic-power-steering", {
          name: "電子轉向系統 (EPS)",
          ai: "車道維持扭矩輔助 / 自適應轉向手感",
          edge: "駕駛風格辨識 + 即時扭矩控制",
          chip: "Renesas RH850 / Infineon AURIX",
          priority: "mid",
          vendors: ["Renesas", "Infineon"],
          tags: ["eps", "torque"],
        }),
        product("chassis-active-suspension-system", {
          name: "主動懸吊系統",
          ai: "路面掃描預測 + 乘坐舒適度 AI 調節",
          edge: "頻域分析 + 預測控制 MPC",
          chip: "NXP S32Z / TI C2000",
          priority: "mid",
          vendors: ["NXP", "TI"],
          tags: ["suspension", "mpc"],
        }),
        product("chassis-smart-brake-system", {
          name: "智慧煞車系統 (EMB/BBW)",
          ai: "煞車力道預測分配 / AEB 執行端",
          edge: "<5ms 即時推論 + 功能安全冗餘",
          chip: "Infineon AURIX TC4xx (ASIL-D)",
          priority: "high",
          vendors: ["Infineon"],
          tags: ["braking", "asil-d"],
        }),
        product("chassis-tire-pressure-monitoring-system", {
          name: "胎壓監測系統 (TPMS)",
          ai: "輪胎壽命預測 / 漏氣趨勢預警",
          edge: "時序異常偵測 + 溫壓融合模型",
          chip: "Infineon SP49 + 專用 MCU",
          priority: "low",
          vendors: ["Infineon"],
          tags: ["tpms", "prediction"],
        }),
      ],
    },
    {
      id: "v2x",
      icon: "📡",
      category: "V2X 車聯網通訊",
      color: "#6A4C93",
      summary: "串接車端、路側與雲端資訊流，支援協同感知與軟體更新閉環。",
      products: [
        product("v2x-c-v2x-module", {
          name: "C-V2X 通訊模組 (PC5/Uu)",
          ai: "交叉路口碰撞預警 / 協同感知融合",
          edge: "Cooperative Perception + 時空圖推論",
          chip: "Qualcomm 9150 / Autotalks Tekton3",
          priority: "high",
          vendors: ["Qualcomm", "Autotalks"],
          tags: ["v2x", "cooperative-perception"],
        }),
        product("v2x-roadside-unit", {
          name: "V2X 路側單元 (RSU)",
          ai: "交通流量分析 / 行人過街意圖預測",
          edge: "多攝影機跨視角追蹤 + 群體行為預測",
          chip: "NVIDIA Jetson Orin Nano / Qualcomm SA6155P",
          priority: "mid",
          vendors: ["NVIDIA", "Qualcomm"],
          tags: ["rsu", "traffic"],
        }),
        product("v2x-hd-map-update-module", {
          name: "高精地圖更新模組",
          ai: "眾包地圖差異偵測 / 車道級定位修正",
          edge: "視覺 SLAM + 語意變化偵測",
          chip: "域控制器搭載 / Mobileye REM",
          priority: "mid",
          vendors: ["Mobileye"],
          tags: ["hd-map", "slam"],
        }),
        product("v2x-ota-update-manager", {
          name: "OTA 遠端更新管理器",
          ai: "差分更新策略 / 更新失敗預測與回滾",
          edge: "A/B 分區管理 + 異常預警模型",
          chip: "NXP S32G3 Gateway SoC",
          priority: "mid",
          vendors: ["NXP"],
          tags: ["ota", "gateway"],
        }),
      ],
    },
    {
      id: "lighting",
      icon: "💡",
      category: "智慧照明系統",
      color: "#E76F51",
      summary: "把場景辨識、光型控制與動態投影能力引入車身照明系統。",
      products: [
        product("lighting-matrix-led-headlamp", {
          name: "矩陣式 LED 頭燈 (ADB)",
          ai: "對向來車遮蔽 / 行人高亮標示",
          edge: "即時物件追蹤 → 像素級光型控制",
          chip: "Infineon LITIX + AURIX / TI TPS929",
          priority: "high",
          vendors: ["Infineon", "TI"],
          tags: ["headlamp", "adb"],
        }),
        product("lighting-dlp-projector-headlamp", {
          name: "數位微鏡 (DLP) 投影頭燈",
          ai: "路面投射資訊 (導航/警告/動畫)",
          edge: "場景識別 → 動態投影內容生成",
          chip: "TI DLP5534-Q1 + 專用 SoC",
          priority: "mid",
          vendors: ["TI"],
          tags: ["dlp", "projection"],
        }),
        product("lighting-ambient-control-module", {
          name: "氛圍燈控制模組",
          ai: "情境感知燈光 (音樂/駕駛模式/疲勞)",
          edge: "情緒推論 + 色彩場景映射",
          chip: "OSRAM OSIRE / NXP LPC MCU",
          priority: "low",
          vendors: ["OSRAM", "NXP"],
          tags: ["ambient", "emotion"],
        }),
        product("lighting-v2v-light-communication", {
          name: "智慧尾燈通訊 (V2V Light)",
          ai: "光通訊 (LiFi) 車間訊息傳遞",
          edge: "調變解調 + 簡單訊息分類",
          chip: "專用光通訊 IC + MCU",
          priority: "low",
          vendors: ["Custom"],
          tags: ["lifi", "v2v"],
        }),
      ],
    },
    {
      id: "parking",
      icon: "🅿️",
      category: "自動泊車與停車",
      color: "#264653",
      summary: "以低速自駕、BEV 車位理解與路徑規劃建構停車體驗閉環。",
      products: [
        product("parking-automatic-parking-assist", {
          name: "自動泊車系統 (APA/RPA)",
          ai: "車位偵測 / 路徑規劃 / 自動轉向控制",
          edge: "BEV 車位分割 + RRT* 路徑規劃",
          chip: "TI TDA4VH / NVIDIA Orin",
          priority: "high",
          vendors: ["TI", "NVIDIA"],
          tags: ["apa", "rrt"],
        }),
        product("parking-autonomous-valet-parking", {
          name: "自主代客泊車 (AVP)",
          ai: "無人低速自駕 / 地下停車場 SLAM 導航",
          edge: "視覺 SLAM + 局部路徑規劃",
          chip: "NVIDIA Orin / Qualcomm Ride",
          priority: "mid",
          vendors: ["NVIDIA", "Qualcomm"],
          tags: ["avp", "slam"],
        }),
        product("parking-spot-detection-camera", {
          name: "車位偵測攝影機",
          ai: "空位辨識 / 車牌識別 / 停車計時",
          edge: "輕量分類模型 + OCR",
          chip: "Ambarella CV25 / HiSilicon",
          priority: "low",
          vendors: ["Ambarella", "HiSilicon"],
          tags: ["parking", "ocr"],
        }),
      ],
    },
    {
      id: "body",
      icon: "🚗",
      category: "車身電子與舒適",
      color: "#8D99AE",
      summary: "將舒適性、視覺輔助與場景自動化延伸到整車車身電子。",
      products: [
        product("body-body-control-module", {
          name: "車身控制模組 (BCM)",
          ai: "智慧進入 / 預測性門鎖 / 情境聯動",
          edge: "行為預測 + 場景規則引擎",
          chip: "NXP S32K3 / Infineon AURIX Lite",
          priority: "mid",
          vendors: ["NXP", "Infineon"],
          tags: ["bcm", "comfort"],
        }),
        product("body-camera-monitor-system", {
          name: "數位後視鏡 (CMS)",
          ai: "後方物件偵測 / 夜間影像增強 / 盲點警示",
          edge: "即時影像增強 ISP + CNN 推論",
          chip: "Ambarella CV72 / TI TDA4",
          priority: "mid",
          vendors: ["Ambarella", "TI"],
          tags: ["cms", "night-vision"],
        }),
        product("body-smart-seat-controller", {
          name: "智慧座椅控制器",
          ai: "壓力分佈分析 / 坐姿矯正 / 疲勞緩解按摩",
          edge: "壓力矩陣分類 + 時序疲勞模型",
          chip: "專用 MCU + 壓力感測陣列",
          priority: "low",
          vendors: ["Custom"],
          tags: ["seat", "comfort"],
        }),
        product("body-smart-wiper-controller", {
          name: "智慧雨刷控制器",
          ai: "雨量強度辨識 / 自適應刷速控制",
          edge: "輕量影像分類模型",
          chip: "車用 MCU + 雨滴感測器",
          priority: "low",
          vendors: ["Custom"],
          tags: ["wiper", "vision"],
        }),
        product("body-auto-dimming-mirror", {
          name: "電子後視鏡自動防眩",
          ai: "後方強光偵測 / 漸變調光",
          edge: "光線強度分類 + 調光控制",
          chip: "專用光感 IC + MCU",
          priority: "low",
          vendors: ["Custom"],
          tags: ["mirror", "dimming"],
        }),
      ],
    },
    {
      id: "fleet",
      icon: "🚛",
      category: "車隊管理與後市場",
      color: "#3D5A80",
      summary: "延伸到營運端，支援車隊可視化、保險定價與預測性維護。",
      products: [
        product("fleet-dashcam", {
          name: "行車記錄器 (DVR/Dashcam)",
          ai: "事件自動標記 / 碰撞偵測 / 危險駕駛辨識",
          edge: "影像事件分類 + G-sensor 融合",
          chip: "Ambarella H32 / Novatek NT96580",
          priority: "high",
          vendors: ["Ambarella", "Novatek"],
          tags: ["dashcam", "fleet"],
        }),
        product("fleet-edge-gateway", {
          name: "車載邊緣閘道器 (Edge Gateway)",
          ai: "CAN 匯流排異常偵測 / 預測性維護",
          edge: "時序異常偵測 + Federated Learning",
          chip: "NXP S32G3 / Renesas R-Car S4",
          priority: "mid",
          vendors: ["NXP", "Renesas"],
          tags: ["gateway", "predictive-maintenance"],
        }),
        product("fleet-ubi-obd-module", {
          name: "UBI 車險 OBD 模組",
          ai: "駕駛行為評分 / 風險定價模型",
          edge: "加速度特徵提取 + 輕量 ML 評分",
          chip: "車用 OBD MCU + BLE/4G",
          priority: "mid",
          vendors: ["Custom"],
          tags: ["ubi", "insurance"],
        }),
        product("fleet-ai-black-box", {
          name: "車載 AI 黑盒子",
          ai: "全車 ECU 日誌分析 / 事故重建",
          edge: "多源資料壓縮 + 異常序列偵測",
          chip: "NXP S32G + eMMC 儲存",
          priority: "low",
          vendors: ["NXP"],
          tags: ["black-box", "forensics"],
        }),
      ],
    },
  ],
  trendInsights: [
    {
      id: "chip-platforms",
      title: "主流推論晶片",
      items: [
        "NVIDIA Orin 系列、Qualcomm Ride/SA8295P、TI TDA4、Renesas R-Car V4H、Ambarella CV7x",
      ],
    },
    {
      id: "frameworks",
      title: "關鍵 AI 框架",
      items: ["TensorRT、SNPE、TIDL、ONNX Runtime、TFLite，並以 INT8 量化部署為主流。"],
    },
    {
      id: "safety-standards",
      title: "安全與法規標準",
      items: ["ISO 26262 ASIL-B/D、SOTIF ISO 21448、Cybersecurity ISO/SAE 21434。"],
    },
    {
      id: "market-drivers",
      title: "市場驅動力",
      items: ["L2+ ADAS 法規推進、SDV 軟體定義車輛、EV 能源最佳化、座艙個人化體驗。"],
    },
  ],
});
